### ISSUE TITLE
TODO: Operations

### ISSUE THREAD

**Issue by sbotor** [sbotor/budget-manager#1]
# TODO for all operation-related stuff. Most of these are low-priority and very simple.

- [ ] **Improve operation info by adding:**
   - [ ] Source/destination info (account's user username, preferably using account.get_username()) if the operation is a transaction.
   - [ ] Plan info if the operation is the result of a plan. I think the next date will suffice.

The Operation model has both these pieces of information already.

- [ ] **Implement operation adding from the extended history menu:**
   - [ ] Add the button and modal (via `include`) to the html.
   - [ ] Implement adding the operation in the `OpHistoryView` similar to the `UserView`.

- [ ] **Add a finalize all button to the extended operation history:**
   - [ ] Add a button and an appropirate confirmation modal.
   - [ ] Process the data in the View. Add a `finalize_operations()` method to the Account class.
