### ISSUE TITLE
TODO: Home

### ISSUE THREAD

**Issue by sbotor** [sbotor/budget-manager#2]
# TODO for all Home-related stuff. This is more important.

- [ ] **Make the home user list pretty***

- [ ] **Implement giving the Admin role to another user:**
   - [ ] Button, confirmation modal. Visible only to the admin.
   - [ ] View. Use `change_admin()` method from the Home model.

- [ ] **Implement Home deletion:**
   - [ ] Button, modal. Make it almost scream at the user. Maybe not a modal but an entire page even. Visible only to the admin ofc.
   - [ ] Implement in the back-end. Maybe with a static method similar to `create_home()`.
