### ISSUE TITLE
TODO: General

### ISSUE THREAD

**Issue by sbotor** [sbotor/budget-manager#3]
# TODO for general things

- [ ] **Data validation. There is almost none.**
   - [ ] Do something if `form.is_valid()` is False.

- [ ] **Make messages pretty. They are in the `base.html` template in the *messages* block.**
